version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      
      - checkout

      - run:
          name: Running with test coverage and send to codecov
          command: |
            go get -u github.com/jstemmer/go-junit-report
            mkdir -p $TEST_RESULTS
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            go test ./... -cover -race -mod=vendor -coverprofile=coverage.txt -covermode=atomic | tee ${TEST_RESULTS}/go-test.out
            bash <(curl -s https://codecov.io/bash)

      - run:
          name: Running linter
          command: |
            sudo chown circleci:circleci /go/bin
            curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.14.0
            golangci-lint run      

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results